### ISSUE TITLE
Accept more file names than just goke.yml for configuration files

### ISSUE THREAD

**Issue by flythenimbus** [dugajean/goke#2]
Other valid file names could be:

- goke.yaml
- goke.dist.yml

Longer file names would be prioritized when loading them file name.

**Comment by reneManqueros** [comment]
What about having a cli flag like -config=goke.dev.yaml where the user can specify the file?

**Comment by flythenimbus** [comment]
That's not a bad idea. Do you wanna throw in a ticket for this one as I already implemented this ticket in #15

**Comment by reneManqueros** [comment]
OK, i'll extend #15 to take one from the command line, speaking of, what did you think about moving to cobra or the Flag modules for parsing the cli params?
