### ISSUE TITLE
Refactor Parser for unit tests

### ISSUE THREAD

**Issue by samthom** [dugajean/goke#24]
Refactor _parser.go_, change _Parser_ struct to interface and create mocks using [mockery](https://github.com/vektra/mockery) for better unit tests.

Refactor unit tests and add rest of the tests.

**Comment by flythenimbus** [comment]
Just FYI that I'm already working on adding tests for the executor struct. We'll see how we can combine our efforts.

**Comment by samthom** [comment]
@dugajean Looks like there is cycle dependency issue if we move _ParseCommandLine()_ from _internal/util.go_ to _internal/cli/util.go_ since we are using _internal_ package inside _options.go_ and _ParseCommandLine()_ inside Executor.
We might have to change the package structure to accommodate new changes.
