### ISSUE TITLE
Additional unit tests

### ISSUE THREAD

**Issue by flythenimbus** [dugajean/goke#4]
Write more unit tests for the Executor struct, Parser and Lockfile. Mocks for common file operations are already present under `internal/tests/stdlib_wrapper_mock.go`.

**Comment by samthom** [comment]
@dugajean Can I update the _parser.go_ and add an interface so it will be easy to mock and write unit test for the struct ?

**Comment by flythenimbus** [comment]
@samthom Go for it. But I'd appreciate it if you created an issue for that.
